config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/projects', to: 'static_pages#projects',   via: 'get'
  resources :users, only: [:show, :destroy]
  resources :posts do 
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :user_id, :post_id,  presence: true
  validates :body, presence: true, length: { minimum:15 }


end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many   :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum:10, maximum:50 }, uniqueness: true
  validates :body, presence: true,  length: { minimum:130 }

  def self.search(query)
    where("title like ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, dependent: :destroy
  has_many :comments,  dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def checks_is_admin
      authenticate_user!

      if current_user.admin
        return
      else
        flash[:notice] = "Access is denied"
        redirect_to root_url
      end
    end

    def after_sign_up_path_for(resource)
      user_path(resource)
    end

    def after_sign_in_path_for(resource)
      user_path(resource)
    end

    def render_404
      render :file => 'public/404.html.haml', status: :not_found, layout: 'application'
    end

    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js   
      end
    else
      flash[:error] = "Sign in please"
    end
     #redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if (@comment.user == current_user) || current_user.admin?
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js  
      end
    else
      flash[:error] = "Access denied"
    end

    #redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :checks_is_admin, except: [:index, :show] 
  before_action :find_post,       only:   [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC").paginate(page:params[:page], per_page: 10)
      render_404  if @posts.count == 0
    else
      @posts = Post.all.order('created_at DESC').paginate(page:params[:page], per_page: 4)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created"
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post successfully saved"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post deleted"
      redirect_to posts_path
    else
      render 'index'
    end
  end

  def find_post
    @post = Post.find(params[:id])
  end


  private

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def correct_user
      @post = Post.find(params[:id])
      redirect_to(root_url) unless (@post.user_id == current_user.id) || current_user.admin?
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def contact
  end

  def projects
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :current, only: [:show]
before_action :checks_is_admin, only: [:destroy] 

  def show
    @posts = current_user.posts.paginate(page:params[:page], per_page: 50)
  end

  def destroy
    user = User.find(params[:id])
    if (current_user == user) && (current_user.admin?)
      flash[:error] = "Can not delete own admin account!"
    else
      user.destroy
      flash[:success] = "User deleted"
    end
    redirect_to user_path(current_user)

  end

  private

    def current
      @user = User.find(params[:id])
      if @user == current_user 
        return
      else
        flash[:error] = "Please sign in"
        redirect_to root_path
       end   
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "The blog of Abyanov Bulat"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.comments
  %p 
    %strong Commenter: 
    =comment.user.email
  %p.comment
    %strong Body:  
    =comment.body.html_safe
  %span.comment-post Posted #{ time_ago_in_words(comment.created_at) } ago. 
= link_to 'Delete', [comment.post, comment], method: :delete, :remote => true, data: { confirm: 'Are you sure?' } if (comment.user == current_user) || current_user.try(:admin?)

app/views/comments/create.js.erb
$('#comments-js').html("<%=j render @post.comments %>");
document.getElementById('com').value='';

app/views/comments/destroy.js.erb
$('#comments-js').html("<%=j render @post.comments %>");

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value| 
  = content_tag(:div, value, class: "alert alert-#{key}") 

app/views/layouts/_footer.html.haml
%footer.footer
  .copyright
    %p.copy Copyright &copy; 2014 Abyanov Bulat
    %strong Russia, Kazan.

app/views/layouts/_logo.html.haml
.row
  .span9
    .banner
      = link_to "Abyanov Bulat", root_path, class: "logo"

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/_sidebar.html.haml
.span2.sidebar
  %ul
    %li= link_to "Home",     root_path,     class: "button" 
    %li= link_to "Projects", projects_path, class: "button" 
    %li= link_to "Blog",     posts_path,    class: "button" 
    %li= link_to "Contact",  contact_path,  class: "button" 
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title)) 
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
    = render 'layouts/shim' 
  %body
    #wrap
      .content 
        .container
          = render 'layouts/logo' 
          .row
            #user_nav
              - if user_signed_in?
                Signed in as #{link_to current_user.email, user_path(current_user)} 
                = link_to "Sign out", destroy_user_session_path, :method => :delete 
              - else 
                = link_to "Sign up", new_user_registration_path 
                or #{link_to "sign in", new_user_session_path}
            = render 'layouts/flash_messages' 

            = render 'layouts/sidebar' 
            .span7
              = yield 
      = render 'layouts/footer' 

app/views/posts/_form.html.haml
= form_for @post do |f| 
  = render 'shared/error_messages' 
  %p
    = f.label :title 
    = f.text_field :title , class: "post-form"
  %p.post-form
    = f.label :body
    = f.text_area :body, size: "90x20" , class: "post-form"
  %p
    = f.submit "Save post", class: "btn" 

app/views/posts/edit.html.haml
- provide(:title, "Edit post")
%h1 Edit post

= render 'form' 

app/views/posts/index.html.haml
- provide(:title, 'Blog')
= render 'shared/search'
%h1 Latest Posts
.posts
  - @posts.each do |post|
    %h2.posts-h2= link_to post.title, post_path(post)
    %span.created-post= l(post.created_at, format: :created_post)
    %p
      = truncate(post.body.html_safe, length: 300, separator: ' ', escape: false)
      = link_to "Continue",  post_path(post)
    - if current_user.try(:admin?)
      = link_to "Edit", edit_post_path(post)
      = link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }
= will_paginate

app/views/posts/new.html.haml
- provide(:title, 'New post')
%h1 New post

= render 'form' 

app/views/posts/show.html.haml
- provide(:title, @post.title) 
.posts
  %h1= @post.title
  %p=  @post.body.html_safe
  = link_to "Back", posts_path
%h2
  %strong Comments
.comments-wrap
  #comments-js= render @post.comments
  - if user_signed_in?
    %h2 Add a comment:
    = form_for([@post, @post.comments.build], remote: true) do |f| 
      %p
        = f.text_area :body, size: "90x5",class: "post-form-comment", id: "com"
      = f.submit "Post comment",  class: "btn"
  - else
    %p
      %strong #{link_to "Sign up", new_user_registration_path } or #{link_to "sign in", new_user_session_path} to leave a comment.

app/views/shared/_error_messages.html.haml
- if @post.errors.any? 
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(@post.errors.count, "error")}
    %ul
      -@post.errors.full_messages.each do |msg| 
        %li * #{msg}

app/views/shared/_search.html.haml
%form{:action => posts_path, :method => "get"}
  = text_field_tag :search, params[:search], class: "input-xlarge input-search",placeholder: "Search Posts"
  = submit_tag "Search", class: "btn btn-mini", :name => nil

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact Information
%p
  You can contact me by e-mail:
  %strong gclank.pryd@gmail.com

app/views/static_pages/home.html.haml
%h1 Junior Ruby on Rails Developer 
%p Hello! My name is Abyanov Bulat. I'm junior ruby on rails developer. 
%p Skills:
%ul
  %li Ruby/Ruby on Rails
  %li HTML5/CSS3
  %li Git
  %li SQL
  %li TDD/BDD
%p Likes:
%ul
  %li Basketball
  %li Good music
  %li Cars

app/views/static_pages/projects.html.haml
- provide(:title, 'Projects') 
%h1 Projects

app/views/users/show.html.haml
%p
  %strong Name: #{current_user.name}
  = link_to "Edit profile", edit_user_registration_path(@user)
- if current_user.try(:admin?)
  %p
    %strong You is the admin of this site.
  %span All users: #{User.all.count}
  - User.all.each do |user|
    %ul
      %li= user.email
      = link_to "Delete user" , user_path(user), method: :delete, data: { confirm: "Are you sure?" }
  %p All posts: #{Post.all.count}
  = link_to "Create new post", new_post_path
- else
%p Your posts #{current_user.posts.count}
- @posts.each do |post|
  %ul
    %li= link_to post.title, post_path(post)
%p Your comments #{current_user.comments.count}
- current_user.comments.each do |comment|
  %ul
    %li Post: #{comment.post.title} , comment: #{link_to comment.body, post_path(comment.post)}
= will_paginate @posts